input_sheet: "Factura"

output_sheet: "Facturas"

table_name: "TablaFacturas"

columns:
  - Mes_facturado
  - Suministro
  - E_Activa
  - E_hora_punta
  - E_fuera_punta
  - Energia_Inductiva
  - Potencia_HP
  - Potencia_FP
